package com.booktracker.app.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1A73E8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE3F2FD)
val md_theme_light_onPrimaryContainer = Color(0xFF0B2A4D)
val md_theme_light_secondary = Color(0xFF667085)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF2F4F8)
val md_theme_light_onSecondaryContainer = Color(0xFF1D2733)
val md_theme_light_tertiary = Color(0xFF6D5F4A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF4EBDD)
val md_theme_light_onTertiaryContainer = Color(0xFF2A2217)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFF5F6FA)
val md_theme_light_onBackground = Color(0xFF111827)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF111827)
val md_theme_light_surfaceVariant = Color(0xFFF2F4F8)
val md_theme_light_onSurfaceVariant = Color(0xFF7A8495)
val md_theme_light_outline = Color(0xFFE3E7EE)
val md_theme_light_inverseOnSurface = Color(0xFFF4F6FA)
val md_theme_light_inverseSurface = Color(0xFF1C2129)
val md_theme_light_inversePrimary = Color(0xFF8AB4F8)

val md_theme_dark_primary = Color(0xFF8AB4F8)
val md_theme_dark_onPrimary = Color(0xFF0B2A4D)
val md_theme_dark_primaryContainer = Color(0xFF153A66)
val md_theme_dark_onPrimaryContainer = Color(0xFFE6F0FF)
val md_theme_dark_secondary = Color(0xFFB7C0CC)
val md_theme_dark_onSecondary = Color(0xFF2A313B)
val md_theme_dark_secondaryContainer = Color(0xFF353D47)
val md_theme_dark_onSecondaryContainer = Color(0xFFEEF1F6)
val md_theme_dark_tertiary = Color(0xFFD7C7B1)
val md_theme_dark_onTertiary = Color(0xFF3A2F22)
val md_theme_dark_tertiaryContainer = Color(0xFF514434)
val md_theme_dark_onTertiaryContainer = Color(0xFFF4EBDD)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF0F1217)
val md_theme_dark_onBackground = Color(0xFFE5E9F0)
val md_theme_dark_surface = Color(0xFF151A21)
val md_theme_dark_onSurface = Color(0xFFE5E9F0)
val md_theme_dark_surfaceVariant = Color(0xFF1E232B)
val md_theme_dark_onSurfaceVariant = Color(0xFFB7C0CC)
val md_theme_dark_outline = Color(0xFF2C333D)
val md_theme_dark_inverseOnSurface = Color(0xFF11141A)
val md_theme_dark_inverseSurface = Color(0xFFE5E9F0)
val md_theme_dark_inversePrimary = Color(0xFF1A73E8)
